package org.jcnc.snow.cli.utils;

public class ProjectCloudExample {
    /**
     * 工具类构造方法，禁止实例化。
     */
    private ProjectCloudExample() {
        // 工具类不允许实例化
    }

    /**
     * 获取 main.snow 示例模块的内容字符串。
     *
     * @return main.snow 示例模块的完整代码
     */
    public static String getProjectCloud() {
        return """
                # Generated by snow init
                project {
                    group    = "com.example"
                    artifact = "demo-app"
                    version  = "0.0.1-SNAPSHOT"
                }
                
                build {
                    srcDir = "src"
                    output = "build/demo-app"
                }
                """;
    }
}
