if(NOT DEFINED DOC_PATH OR "${DOC_PATH}" STREQUAL "")
  message(FATAL_ERROR "DOC_PATH is required")
endif()

if(NOT EXISTS "${DOC_PATH}")
  message(FATAL_ERROR "Required doc does not exist: ${DOC_PATH}")
endif()

file(READ "${DOC_PATH}" DOC_TEXT)
string(TOLOWER "${DOC_TEXT}" DOC_TEXT_LOWER)

if(DEFINED REQUIRED_PATTERNS AND NOT "${REQUIRED_PATTERNS}" STREQUAL "")
  set(PATTERN_SOURCE "${REQUIRED_PATTERNS}")
  string(REPLACE "\"" "" PATTERN_SOURCE "${PATTERN_SOURCE}")
  string(REPLACE "'" "" PATTERN_SOURCE "${PATTERN_SOURCE}")
  string(REPLACE "|" ";" PATTERN_LIST "${PATTERN_SOURCE}")
  foreach(pattern IN LISTS PATTERN_LIST)
    string(STRIP "${pattern}" PATTERN_TEXT)
    if(PATTERN_TEXT STREQUAL "")
      continue()
    endif()
    string(TOLOWER "${PATTERN_TEXT}" PATTERN_LOWER)
    string(FIND "${DOC_TEXT_LOWER}" "${PATTERN_LOWER}" PATTERN_INDEX)
    if(PATTERN_INDEX EQUAL -1)
      message(FATAL_ERROR "Required pattern not found in ${DOC_PATH}: ${PATTERN_TEXT}")
    endif()
  endforeach()
endif()
